import { Link, NavLink, Outlet } from 'react-router-dom'

function PublicLayout() {
  return <div className="min-h-screen bg-canvas text-navy-950"><header className="border-t-4 border-saffron bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between gap-5 px-5 py-5 sm:px-8"><Link to="/" className="text-xl font-bold tracking-tight">ANVESH</Link><nav className="flex items-center gap-4 text-sm font-semibold text-muted sm:gap-6"><NavLink to="/" end>Home</NavLink><NavLink to="/about">About ECDAT</NavLink><NavLink to="/why-cbom">Why CBOM</NavLink><Link to="/login" className="rounded-lg bg-navy-800 px-3 py-2 text-white">Sign in</Link></nav></div></header><main><Outlet /></main><footer className="border-t border-line bg-white py-6 text-center text-sm text-muted">ECDAT is a read-only cryptographic discovery and migration advisory tool.</footer></div>
}

export function HomePage() {
  return <><section className="public-hero border-b border-line"><div className="mx-auto max-w-6xl px-5 py-24 sm:px-8"><p className="text-sm font-bold uppercase tracking-[0.16em] text-navy-800">Enterprise cryptographic readiness</p><h1 className="mt-4 max-w-3xl text-4xl font-bold tracking-tight text-navy-950 sm:text-6xl">Know where cryptography lives before planning its migration.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted">ECDAT discovers cryptographic assets, links them to evidence, assesses quantum-migration urgency, and presents purpose-aware guidance. It does not alter source systems.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/login" className="rounded-lg bg-navy-800 px-5 py-3 text-sm font-semibold text-white">Open the dashboard</Link><Link to="/why-cbom" className="rounded-lg border border-line bg-white px-5 py-3 text-sm font-semibold text-navy-950">See the CBOM flow</Link></div></div></section><section className="mx-auto grid max-w-6xl gap-5 px-5 py-14 sm:grid-cols-3 sm:px-8"><article className="rounded-xl border border-line bg-white p-6"><h2 className="font-bold">Evidence-backed inventory</h2><p className="mt-3 text-sm leading-6 text-muted">Every finding retains its detection method, rule, source location, and confidence.</p></article><article className="rounded-xl border border-line bg-white p-6"><h2 className="font-bold">Explainable priority</h2><p className="mt-3 text-sm leading-6 text-muted">Mosca X, Y, and Z values and HNDL exposure make quantum risk auditable.</p></article><article className="rounded-xl border border-line bg-white p-6"><h2 className="font-bold">Purpose-aware migration</h2><p className="mt-3 text-sm leading-6 text-muted">Key establishment and digital-signature assets receive distinct NIST PQC guidance.</p></article></section></>
}

export function AboutPage() { return <section className="mx-auto max-w-4xl px-5 py-18 sm:px-8"><p className="text-xs font-bold uppercase tracking-[0.16em] text-navy-800">About ECDAT</p><h1 className="mt-3 text-4xl font-bold tracking-tight">Compliance-oriented cryptographic discovery.</h1><div className="mt-8 space-y-5 text-base leading-8 text-muted"><p>ECDAT is an evidence-backed, read-only decision-support prototype for organizations preparing their cryptography for post-quantum migration. It connects discovery, reachability, Mosca risk assessment, and migration impact analysis in one workflow.</p><p>Its classification and readiness framing align with TEC 910018:2025. Its primary replacement guidance distinguishes NIST-standardized ML-KEM (FIPS 203), ML-DSA (FIPS 204), and SLH-DSA (FIPS 205), while keeping algorithms still under standardization out of primary recommendations.</p><p>The prototype supports source code and certificates, with a call-graph reachability view. Broader infrastructure, container, and continuous-monitoring coverage remain explicit roadmap items.</p></div></section> }

export function WhyCbomPage() { return <section className="mx-auto max-w-5xl px-5 py-18 sm:px-8"><p className="text-xs font-bold uppercase tracking-[0.16em] text-navy-800">Why CBOM</p><h1 className="mt-3 text-4xl font-bold tracking-tight">A cryptographic bill of materials makes migration reviewable.</h1><p className="mt-5 max-w-3xl leading-7 text-muted">A CBOM captures the cryptographic assets, their evidence, risk, and recommendations as an auditable export. It turns scattered implementation details into a structured basis for planning.</p><div className="mt-12 grid items-center gap-4 text-center md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr]"><FlowBox title="Discovery" text="Source and certificates"/><Arrow/><FlowBox title="CBOM" text="Evidence-backed inventory"/><Arrow/><FlowBox title="Risk" text="Mosca and HNDL context"/><Arrow/><FlowBox title="Migration" text="Purpose-aware roadmap"/></div></section> }

function FlowBox({ title, text }: { title: string; text: string }) { return <div className="rounded-xl border border-line bg-white p-5"><p className="font-bold text-navy-950">{title}</p><p className="mt-2 text-xs leading-5 text-muted">{text}</p></div> }
function Arrow() { return <span className="hidden text-2xl text-navy-800 md:block">→</span> }

export default PublicLayout
